env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
overrides:
  - files: ["*.mjs"]
    parserOptions:
      sourceType: module
parserOptions:
  ecmaVersion: latest
rules: {}
